### PR TITLE
Send world announce on a user kick by AntiCheat.

### PR DESCRIPTION
**Pull request by masterking32**
Add kick announce.

### CODE REVIEW

**Comment by Deku** [comment]
Maybe you could refactor the message sending into a separate method so we don't have duplicates and it's easier to reuse in the future.

**Comment by BarbzYHOOL** [comment]
@masterking32 :D

**Comment by Helias** [comment]
What about merge @BarbzYHOOL, @masterking32 ?

**Comment by masterking32** [comment]
IDK xD

**Pull request merged**
