### PR TITLE
Upgrade module

### PR DESCRIPTION
**Pull request by pangolp**
## Changes Proposed:
-  Temporary patch, for future people who use the module, so that they do not have to load the SQL manually.
-  Until the module detects the base files first, and then updates them, this is the only way the module will work when run for the first time.

## Issues Addressed:

- Closes 

## Tests Performed:

- Windows 10
- In-game

## How to Test the Changes:

1. Add the module.
2. Enter with a character to the kingdom.
3. The server no longer crashes, because the SQL is up to date. You don't have to do it manually.
4. Without this change, you are forced to apply the changes manually. Because if not, the emulator detects that the tables are not updated.
5. Maybe it is not the best solution, but at least it is a solution for future users. Those who already have the module should sacrifice the tables or continue updating it manually.

## Screenshot

no_crash_report

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
The anticheat module uses its own update system that needs to be removed if you’re going to use the default auto updater

**Comment by pangolp** [comment]
> The anticheat module uses its own update system that needs to be removed if you’re going to use the default auto updater

Ah, I didn't know that information. Is this change wrong then?

**Comment by pangolp** [comment]
Even though I have merge permissions, I will not approve this change, even though it passes the tests. I leave it in your hands, let them decide if it is useful or not. If not, we go back to the previous files. However, I think I'm going to use it.

**Comment by pangolp** [comment]
Having never used the anticheat so far, this works for me. Perhaps some project, which is already using it, will not use it. Obviously, I don't want to harm anyone. But use the pull request anyway, if it doesn't apply.

**Comment by Nyeriah** [comment]
Disregard what I said as it was already removed

**Comment by pangolp** [comment]
> Disregard what I said as it was already removed

The include? Yeah.

**Comment by pangolp** [comment]
The issue is knowing if this affects in any way the projects that already have the anticheat. It works for new users, but for those who are already using it, I don't know.

**Comment by pangolp** [comment]
Thanks @Nyeriah

**Pull request merged**
