### PR TITLE
New passive anticheat system by kvipka.

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed https://github.com/azerothcore/azerothcore-wotlk/issues/4007.

**AzerothCore version https://github.com/azerothcore/azerothcore-wotlk/commit/2189ac0b0834393f7ad9fed78fdea56f54cd6a8b OR HIGHER is a requirement.**

Fo testing purpose - please disable kick options in config file (if you are sure that players don't use hacks/cheats).
Logs are enough to track false positives (once https://github.com/azerothcore/azerothcore-wotlk/pull/6104 is merged) or you can add that lines to your `worldserver` config file:
```
Appender.Anticheat=2,5,0,Anticheat.log
Logger.anticheat=4,Console Anticheat
```
to have proper logs.

### CODE REVIEW

**Comment by Helias** [comment]
This PR will be really good and it requires a lot of test.
I am really happy to see that someone is working on it :rocket:

**Comment by Footman** [comment]
Tested this anticheat. There are a lot of false positive detections compared to old one. Mostly connected to some Boss spells. I am not sure if it is better yet.

**Comment by UltraNix** [comment]
@Footman Because many changes has been done to the core. Give me more info about that false positives.

**Comment by UltraNix** [comment]
Ready to be reviewed/tested.

**Comment by UltraNix** [comment]
@FrancescoBorzi Done.

**Comment by UltraNix** [comment]
Please - test it.

**Comment by Helias** [comment]
@azerothcore/testers, this is really a good feature and need a lot of tests fo avoid false positive

**Comment by Helias** [comment]
Yes, but we should test also if with flyhack and similar the anti-cheat detect them

**Comment by Hacki95** [comment]
> 
> 
> Well, how do you flyhack? I'll have to download some cheat on internet?

Once saw a youtube video from some guy testing a various known hacks on private servers, maybe if you can find it you can just test out the hacks this guy used? If I find it again I will link it to you on discord.

**Comment by speedrunz** [comment]
there are false positive detections specially on LK fight (10man mode). Here's the log of it.

2021-05-10_23:45:54 Player::CheckOnFlyHack :  FlyHack Detected for Account id : 14, Player Testerrsz (GUID Full: 0x0000000000000008 Type: Player Low: 8)
2021-05-10_23:45:54 Player::========================================================
2021-05-10_23:45:54 Player::CheckOnFlyHack :  playerZ = 840.857056
2021-05-10_23:45:54 Player::CheckOnFlyHack :  normalZ = 0.000000
2021-05-10_23:45:54 Player::CheckOnFlyHack :  checkz = 2.031000
2021-05-10_23:51:10 Player::CheckOnFlyHack :  FlyHack Detected for Account id : 14, Player Testerrsz (GUID Full: 0x0000000000000008 Type: Player Low: 8)
2021-05-10_23:51:10 Player::========================================================
2021-05-10_23:51:10 Player::CheckOnFlyHack :  playerZ = 840.856995
2021-05-10_23:51:10 Player::CheckOnFlyHack :  normalZ = 0.000000
2021-05-10_23:51:10 Player::CheckOnFlyHack :  checkz = 2.031000
2021-05-10_23:52:41 Player::CheckOnFlyHack :  FlyHack Detected for Account id : 11, Player Mezmowr (GUID Full: 0x0000000000000001 Type: Player Low: 1)
2021-05-10_23:52:41 Player::========================================================
2021-05-10_23:52:41 Player::CheckOnFlyHack :  playerZ = 761.502075
2021-05-10_23:52:41 Player::CheckOnFlyHack :  normalZ = 0.000000
2021-05-10_23:52:41 Player::CheckOnFlyHack :  checkz = 2.031000
2021-05-10_23:52:58 Player::CheckOnFlyHack :  FlyHack Detected for Account id : 14, Player Testerrsz (GUID Full: 0x0000000000000008 Type: Player Low: 8)
2021-05-10_23:52:58 Player::========================================================
2021-05-10_23:52:58 Player::CheckOnFlyHack :  playerZ = 748.446350
2021-05-10_23:52:58 Player::CheckOnFlyHack :  normalZ = 0.000000
2021-05-10_23:52:58 Player::CheckOnFlyHack :  checkz = 2.031000

**Comment by speedrunz** [comment]
additional info. The false positive FlyHack detection usually happens on the phase when he casts Remorseless Winter.

**Comment by UltraNix** [comment]
Somebody else willing to test that module?

**Comment by Sedatyf** [comment]
It's definitively in my backlog, I'll find some time to test it

**Comment by speedrunz** [comment]
Additional Info on ICC 10man normal mode:
- When LK reaches below 40%, he goes to the mid and casts Remorseless Winter (probably when he changes the platform? not sure). This is where the Raging Spirits and other mobs e.g. ghouls fall and is being talked here -> https://github.com/azerothcore/azerothcore-wotlk/pull/5778

- This is the part where the anti-cheat falsely detects us as FlyHackers and kicks us.

How did we test it:
- We're only 2 players with Might of Mograine buff.
- Cheat god is ON (power, casttime, cooldown as well).
- gm fly is OFF
- mod speed is OFF / default 1.

**Comment by UltraNix** [comment]
@speedrunz Write to ome on Discord: UltraNix#5638

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers we need people testing this.

**Comment by poryagholami1374** [comment]
> @azerothcore/testers we need people testing this.

I have enough free time
I am at your service, give orders

**Comment by poryagholami1374** [comment]
This is a good project
Thank you all for your support
People like me who live in a deprived area
 We need such a thing

**Comment by FrancescoBorzi** [comment]
@poryagholami1374 have you tested this PR? can you please share your feedback ?

**Comment by Sedatyf** [comment]
I tried to test this, but I have to say, I'm a bit confused. 
At least, worldserver didn't kicked me for using gm fly. 
If you have some ideas, advices, things to do to test it, please give me a DM in Discord (same name at here) or a comment here

**Comment by UltraNix** [comment]
@Sedatyf Have you tried with some hack tools/ cheat engines?

**Comment by Sedatyf** [comment]
> @Sedatyf Have you tried with some hack tools/ cheat engines?

Not yet. @Branel gave me some cheat engine but it seems there is a lot of harmful files in it. So I have to take time to setup a VM in order to test it

**Comment by Branel** [comment]
They are mostly false positives as a majority of the reports show its safe but please do use a VM just incase.

**Comment by UltraNix** [comment]
@Sedatyf Could you show me your config file from `/bin/builtype/configs/modules/Anticheat.conf`?

**Comment by Sedatyf** [comment]
Sure, here it is @UltraNix 

```config
[worldserver]
#
###################################################################################################

###################################################################################################
#   ANTICHEAT MODULE
#
#     Description: AntiCheats.SafeMode when player udner ACK packet (not handled by core), player will have immune for ASH checks.

AntiCheats.SafeMode.Enabled = 1

#    AntiCheats.FlyHack
#        Description: Enable AntiCheat.FlyHack
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

AntiCheats.FlyHack.Enabled = 1

#    AntiCheats.FlyHack
#        Description: Enable AntiCheat.SpeedHack
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

AntiCheats.SpeedHack.Enabled = 1

#    AntiCheats.DoubleJump.Enabled
#        Description: Enable AntiCheat.DoubleJump Kick when player sent opcode jump when has flag falling (client can't do this)
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

AntiCheats.DoubleJump.Enabled = 1

#    AntiCheats.FakeJumper.Enabled
#        Description: Enable AntiCheat.FakeJumper : when player sent a move opcode (with new Z higher) when has flag falling (client can't sent any new packets when falling)
#		      It's normal for Gagarin hacks and with Air Mode + "space" click = "falling" mode (player can't change orientation of flying, but it move up)
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

AntiCheats.FakeJumper.Enabled = 1

#    AntiCheats.FakeFlyingmode.Enabled
#        Description: Enable AntiCheat.FakeFlyingmode : when player sent a move opcode with added fly flag but on server this flag doesn't restricted for player.
#		      It's normal for Hitchhiker's Hack with Air Mode
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

AntiCheats.FakeFlyingmode.Enabled = 1

#    AntiCheats.IgnoreControlMovement.Enabled
#        Description: Enable AntiCheat.IgnoreControlMovement : when player in root state - client can't send a new movement packets.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AntiCheats.IgnoreControlMovement.Enabled = 1

#
###################################################################################################

###################################################################################################
# Sanctions - Kicks
#
#    AntiCheats.FlyHack.Kick.Enabled
#        Description: Enable AntiCheat.FlyHack Kick when detected
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

AntiCheats.FlyHack.Kick.Enabled = 1

#    AntiCheats.SpeedHack.Kick.Enabled
#        Description: Enable AntiCheat.SpeedHack Kick when detected
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

AntiCheats.SpeedHack.Kick.Enabled = 1

#    AntiCheats.FakeJumper.Kick.Enabled
#        Description: Enable AntiCheats.FakeJumper Kick when detected
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

AntiCheats.FakeJumper.Kick.Enabled = 1

#    AntiCheats.FakeFlyingmode.Kick.Enabled
#        Description: Enable AntiCheats.FakeFlyingmode Kick when detected
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

AntiCheats.FakeFlyingmode.Kick.Enabled = 1

#
###################################################################################################

###################################################################################################
#    AntiCheats.FlyHackTimer
#        Description: Timer for AntiCheat FlyHack check
#        Default:     3000 - 1 check in 3 second (for big projects better (1500ppl +) set 5000 (5 sec) or more)

AntiCheats.FlyHackTimer = 3000

#
###################################################################################################

###################################################################################################
#    AntiCheats.forceExcludeMapsid disabled maps
#        Description: disabled mapid for anticheat system
#        Example:     "616,649"

AntiCheats.forceExcludeMapsid = "616,649"
```
Can I ask why?

**Comment by UltraNix** [comment]
I thought you are using the old one. But looks okay.
Did you enable logs by https://github.com/azerothcore/mod-anticheat/pull/32#issuecomment-836808560?

**Comment by Sedatyf** [comment]
> please test this guys in the Lich King encounter using 2 players so you can see it. Once you reach LK's hp below 40%, one of the players gets falsely flagged as fly hack and then gets kicked. Please try it. I'll buy the testers some beer just to keep this stuff going.

I wanted to try LK's fight but I had a problem after Lady Deathwhisper because I couldn't pass the Gunship Battle. Did you do something specific to go to LK?

**Comment by Sedatyf** [comment]
> I thought you are using the old one. But looks okay.
> Did you enable logs by [#32 (comment)](https://github.com/azerothcore/mod-anticheat/pull/32#issuecomment-836808560)?
> Do you see ingame, in your chat that Anticheat is loaded?
> If you are not using any hacks/engine tools, that would mean there are no false positives. But you should definitely test it with some hack tools.

Forgot about the log thing, I'll definitely try again sometime later

**Comment by Sedatyf** [comment]
Well, I cleaned the rampart by killing mobs and the dragon. Ships came but they were nobody to talk to or launch the event. It was weird @speedrunz

**Comment by FrancescoBorzi** [comment]
>  that would mean there are no false positives.

making sure there are no false positives is also good testing so keep that up too please :)

**Comment by poryagholami1374** [comment]
image
image
Hack Telport
 Does not take

**Comment by UltraNix** [comment]
> image
> image
> Hack Telport
> Does not take

Cannot confirm. I tried that hack tools and everytime it got me kicked. Please - retest it again.

**Comment by UltraNix** [comment]
Hack Teleport is not covered by passive anticheat.

**Comment by UltraNix** [comment]
> image
> image
> Hack Telport
> Does not take

It's just a visual for you. If try to move, you will be kicked out. Everything is alright.

**Comment by poryagholami1374** [comment]
I tested teleport, you were right, it has not been enabled since configuration
I tested something yesterday. When I got on the ulduar tank, I wanted to hack the tank
My game is completely closed

**Comment by speedrunz** [comment]
@mpfans did you enable the logging? If yes, can you paste the output here?

If not, please enable the anticheat logging by adding this in your worldserver.conf 

Logger.anticheat=4,Console Server

**Comment by speedrunz** [comment]
@UltraNix I tried replicating what @mpfans reported and indeed you get kicked instantly after you login when you are on druid bird form.

2021-05-29_03:40:04 MovementHandler::Fake_flying mode (using MOVEMENTFLAG_FLYING flag doesn't restricted) by Account id : 11, Player Testerzs (GUID Full: 0x0000000000000011 Type: Player Low: 17)
2021-05-29_03:45:01 MovementHandler::Fake_flying mode (using MOVEMENTFLAG_FLYING flag doesn't restricted) by Account id : 11, Player Testerzs (GUID Full: 0x0000000000000011 Type: Player Low: 17)

**Comment by UltraNix** [comment]
@mpfans @speedrunz Fixed. Please, retest it.

**Comment by mpfans** [comment]
2021-05-29_22:38:25 PassiveAnticheat: FlyHack Detected for Account id : 5, Player gm (GUID Full: 0x0000000000002d4d Type: Player Low: 11597)
2021-05-29_22:38:25 Player::========================================================
2021-05-29_22:38:25 playerZ = 90.581955
2021-05-29_22:38:25 normalZ = 79.470383
2021-05-29_22:38:25 checkz = 82.738480
2021-05-29_22:38:25 ========================================================
2021-05-29_22:38:28 PassiveAnticheat: FlyHack Detected for Account id : 5, Player gm (GUID Full: 0x0000000000002d4d Type: Player Low: 11597)
2021-05-29_22:38:28 Player::========================================================
2021-05-29_22:38:28 playerZ = 90.581955
2021-05-29_22:38:28 normalZ = 79.470383
2021-05-29_22:38:28 checkz = 82.738480
2021-05-29_22:38:28 ========================================================

**Comment by speedrunz** [comment]
@UltraNix thank you! Druid flightform is now fixed after the commit.

I tested @mpfans new bug discovery by just running the command below and confirmed*, it kicks you in awhile.
.go 1698.317871 792.921570 90.581955 604

**Comment by poryagholami1374** [comment]
When I Go To Incy
 Which is inside the zul dark map
I jumped from a height
And Antichit kicked me
Inside battleground
Jump from a height and test how it will be
I could not test this
But I said you try

**Comment by UltraNix** [comment]
@poryagholami1374 Paste logs.

**Comment by UltraNix** [comment]
@mpfans Fixed.

**Comment by poryagholami1374** [comment]
https://user-images.githubusercontent.com/80007195/120114509-b3c0a700-c194-11eb-914b-d9bf5163dc0a.mp4

HandleSetActiveMoverOpcode: incorrect mover guid: mover is GUID Full: 0xf15000740d0063e7 Type: Vehicle Entry: 29709  Low: 25575 and should be GUID Full: 0xf15000740d0063e8 Type: Vehicle Entry: 29709  Low: 25576
HandleSetActiveMoverOpcode: incorrect mover guid: mover is GUID Full: 0xf15000740d0063e9 Type: Vehicle Entry: 29709  Low: 25577 and should be GUID Full: 0xf15000740d0063ea Type: Vehicle Entry: 29709  Low: 25578
HandleSetActiveMoverOpcode: incorrect mover guid: mover is GUID Full: 0xf15000740d006411 Type: Vehicle Entry: 29709  Low: 25617 and should be GUID Full: 0xf15000740d006412 Type: Vehicle Entry: 29709  Low: 25618

**Comment by speedrunz** [comment]
@poryagholami1374 did you use this commit already?
-> https://github.com/azerothcore/mod-anticheat/pull/32/commits/bbd15c5de952c75f275a043dad9f2808858d5e12

**Comment by UltraNix** [comment]
@poryagholami1374 Update to latest version.

**Comment by mpfans** [comment]
> @poryagholami1374 Update to latest version.

image

**Comment by Kingswow** [comment]
**compile error**  in last version

`Error (active)	E0135	class "Player" has no member "GetTheClosestPoint"	scripts	D:\DT\wow addons\server software\azerothcore-wotlk\modules\mod-anticheat\src\AnticheatData.cpp	222	
`
`Error	C2039	'GetTheClosestPoint': is not a member of 'Player'	scripts	D:\DT\wow addons\server software\azerothcore-wotlk\modules\mod-anticheat\src\AnticheatData.cpp	222	
`
`Error	C3668	'AnticheatPlayerScript::AnticheatResetFallingData': method with override specifier 'override' did not override any base class methods	scripts	D:\DT\wow addons\server software\azerothcore-wotlk\modules\mod-anticheat\src\AnticheatScripts.cpp	66	
`
`Error	C3668	'AnticheatPlayerScript::AnticheatNoFallingDamage': method with override specifier 'override' did not override any base class methods	scripts	D:\DT\wow addons\server software\azerothcore-wotlk\modules\mod-anticheat\src\AnticheatScripts.cpp	71	
`
`Error	C3668	'AnticheatPlayerScript::AnticheatHandleNoFallingDamage': method with override specifier 'override' did not override any base class methods	scripts	D:\DT\wow addons\server software\azerothcore-wotlk\modules\mod-anticheat\src\AnticheatScripts.cpp	76	
`
`Error	C3668	'AnticheatPlayerScript::AnticheatSetSuccessfullyLanded': method with override specifier 'override' did not override any base class methods	scripts	D:\DT\wow addons\server software\azerothcore-wotlk\modules\mod-anticheat\src\AnticheatScripts.cpp	81	
`

**Comment by UltraNix** [comment]
Suspended due to Bountysource inactivity.

**Comment by Kingswow** [comment]
Anticheat Can't Detect **Walk On Water** in sholazar basin

[https://aparat.com/v/1BK5s](url)

Cheat Software : Gagarin v1.7b
AzerothCore rev. a24449436d0b
win 10 64bit


sorry for my bad english

**Comment by Racknar0** [comment]
compile error in last revision

**Comment by UltraNix** [comment]
@Racknar0 I don't see such an error.

**Comment by UltraNix** [comment]
@Kingswow Waterwalk done.
Res At Corpse - you cannot res if you won't move. And if you move before res, then antispeed hack will detect it.

**Comment by speedrunz** [comment]
@FrancescoBorzi this anticheat is 100% working already and has very low false positive rate detection. After testing this, I would say that this should be merged now and have the $300 rewarded to @UltraNix for the tremendous job that he has done to implement this. 

That amount is not even enough for this awesome stuff. I'll definitely buy this man lots of beer. And if any of you appreciates the work that @UltraNix has done for AzerothCore, please don't be shy and give some love to our dear developer.

**Comment by mpfans** [comment]
I don't mind merging now, but there are still many false positives, which still need to be fixed for a long time. I have been in communication with @UltraNix

**Comment by Kingswow** [comment]
> @Kingswow Waterwalk done.
> Can you send link to that Gagarin v1.7b?

https://www.filemail.com/d/fuwllgleuinulcq

**Comment by speedrunz** [comment]
@mpfans what specific false positive are you getting? I've added you on discord as well as I am helping in testing this.

**Comment by Racknar0** [comment]
/home/runner/work/mod-anticheat/mod-anticheat/modules/mod-anticheat/src/AnticheatData.cpp:213:24: fatal error: no member named 'GetTheClosestPoint' in 'Unit'; did you mean 'GetClosePoint'?
                mover->GetTheClosestPoint(cx, cy, cz, 0.5, pz, 6.8f); // first check
                       ^~~~~~~~~~~~~~~~~~
                       GetClosePoint
/home/runner/work/mod-anticheat/mod-anticheat/src/server/game/Entities/Object/Object.h:765:10: note: 'GetClosePoint' declared here
    bool GetClosePoint(float& x, float& y, float& z, float size, float distance2d = 0, float angle = 0, const WorldObject* forWho = nullptr, bool force = false) const;

**Comment by UltraNix** [comment]
@Racknar0 https://github.com/azerothcore/azerothcore-wotlk/pull/6378

**Comment by Kingswow** [comment]
@UltraNix
 **WaterWalk** not fix and work 
**Res At Corps** Work Too 
AzerothCore rev a773c54bd1ba

https://user-images.githubusercontent.com/150390/129676363-1ef97598-f3eb-4e2f-93fa-c479a12478ba.mp4

**Comment by UltraNix** [comment]
@Kingswow Have you updated #6378 on your local? I tested that many times and works for sure.
I didn't say Res At Corps is fixed.

**Comment by Kingswow** [comment]
> @Kingswow Have you updated #6378 on your local? I tested that many times and works for sure.
> I didn't say Res At Corps is fixed.

yes 6378 updated 
i test again and report it here

**Comment by Kingswow** [comment]
> @Kingswow Have you updated #6378 on your local? I tested that many times and works for sure.
> I didn't say Res At Corps is fixed.

i tested everythings step by step 
#6378 is update
#32 is Update
AC is Update 
Masp , DBC , Vmaps And mmaps Is Update 

but **Water Walk** is worked 

Cheat Software : Gagarin 1.7 [Download](https://www.filemail.com/d/fuwllgleuinulcq)
AC Commit 6c8d76b
Win 10 64bit

sry for my bad english

**Comment by UltraNix** [comment]
Yep - Gagarin's waterwalking is undetectable.

**Comment by Kingswow** [comment]
> I don't know how to use `Ress at corpse` hack in Gagarin.

open your wow and login in server 
open your gagarin with run as administrator
in gagarin select refresh and chose process id
select Res At Corps 
Enter the game and die there











sorry for my bad english

**Comment by UltraNix** [comment]
@Kingswow I know how to work with Gagarin. Other hacks work, but this one does not :(

**Comment by Kingswow** [comment]
> @Kingswow I know how to work with Gagarin. Other hacks from Gagarin work, but this one does not :(

@UltraNix No problem bro, you did your job in the best way
It's better for you now than anything else 🥇 ,I'm sure it gets better every day 👍 , **thank you very much** 
.
.
.
.
.
sry for my bad english

**Comment by Kingswow** [comment]
https://aparat.com/v/2tAUZ

`PassiveAnticheat: Fake jumper by Account id : 13, Player Cheat (GUID Full: 0x0000000000000007 Type: Player Low: 7), Mover: (Cheat, GUID Full: 0x0000000000000007 Type: Player Low: 7), Map: 571, Position: X: 5476.2 Y: 4771.33 Z: -200.613 O: 5.48809 (TransportOffsets: None), MovementFlags: 4097`

**Comment by darkenam** [comment]
Anticheat never kick : Teleport hacks ! Anticheat teleport bug. player easy can use teleport hack in maps

**Comment by darkenam** [comment]
@UltraNix 

Anticheat never kick : Teleport hacks ! 

Anticheat teleport bug. 

player easy can use teleport hack in maps

**Comment by UltraNix** [comment]
@darkenam More info needed. What spot? What hack are you using? Steps to reproduce it?

**Comment by darkenam** [comment]
@UltraNix 

speed hack and fly hack  worked just for all cheat hacks  teleport not worked

**Comment by Kingswow** [comment]
@darkenam 
Can you send download link to that Kicker?

**Comment by darkenam** [comment]
program name

hichhicker

admin panel hack

**Comment by Kingswow** [comment]
anticheat work perfect with "The Hitchhiker's Hack" and "Wow admin panel" teleport hack 

@darkenam u sure your anticheat is enable in config ? 

and can u tell me where are u from ?

**Comment by darkenam** [comment]
@Kingswow 
What version did you use? give link

**Comment by Kingswow** [comment]
I use these two links with Azerothcore last revision
azerothcore/azerothcore-wotlk/pull/6378
and
#32

or u can download and compile link below
https://github.com/Kingswow/WNC

**Comment by darkenam** [comment]
some of players on ticket say: we don't use cheat but we get kick of the game!

**Comment by UltraNix** [comment]
@darkenam Because it's still in testing phase. There can be many false positives. Just send to me logs so I can fix it.

**Comment by darkenam** [comment]
@UltraNix

Anticheat, Cakes for no reason in game:

GM & PLAYER

**Comment by UltraNix** [comment]
I made some major changes to config file.
Now every hack type is a seperate submodule. You can choose whether it should be enabled, should send warning to gms or apply penalty to hacker. Every hack submodule has its own configuration and you can set it in the new config file.
Please, update your anticheat module, update the new conf file and modify it to your preferences.
As the false positives: if want to help me to improve that module, you can find on Discord and send to me logs from server.

**Comment by darkenam** [comment]
@UltraNix 

to last update kick not worked, system just give alarm reason to gms!

**Comment by darkenam** [comment]
@UltraNix 


NEED UPDATE !!!

**Comment by zqgmzq** [comment]
switch (applyPenalty)
    {
        case APPLY_PENALTY_NONE:
            return false;
        case APPLY_PENALTY_EVERY_REPORT:
            break;
        default:
        {
            uint32 reportsCount = m_reports[cheatType];
            if (reportsCount < applyPenalty)
            {
                return false;
            }
            break;
        }
    }

**Comment by acidmanifesto** [comment]
Currently the issue this PR was supporting is now closed and no longer needed. I will leave this up in case anyone wishes to use this as a alternative, but as of right now, the current anticheat module has been modernized and has a high success rate and exceedly low false positive now in detection and is worth checking out now.

**Pull request closed without merging**
